"""Pydantic models for the Ted Lasso API."""

from app.models.characters import (
    Character,
    CharacterCreate,
    CharacterUpdate,
    EmotionalStats,
    GrowthArc,
)
from app.models.episodes import Episode, EpisodeCreate, EpisodeUpdate
from app.models.interactive import (
    BelieveRequest,
    BelieveResponse,
    Biscuit,
    CoachingPrinciple,
    ConflictRequest,
    ConflictResolution,
    MatchCommentaryEvent,
    PepTalkChunk,
    PressConferenceRequest,
    PressConferenceResponse,
    ReframeRequest,
    ReframeResponse,
)
from app.models.matches import Match, MatchCreate, MatchUpdate, TurningPoint
from app.models.quotes import Quote, QuoteCreate, QuoteTheme, QuoteUpdate
from app.models.team_members import (
    Coach,
    CoachBase,
    CoachSpecialty,
    CoachUpdate,
    EquipmentManager,
    EquipmentManagerBase,
    EquipmentManagerUpdate,
    MedicalSpecialty,
    MedicalStaff,
    MedicalStaffBase,
    MedicalStaffUpdate,
    MemberType,
    Player,
    PlayerBase,
    PlayerUpdate,
    Position,
    TeamMember,
    TeamMemberCreate,
)
from app.models.teams import GeoLocation, Team, TeamCreate, TeamUpdate, TeamValues
from app.models.websocket import (
    ErrorMessage,
    LiveMatchEvent,
    LiveMatchEventType,
    MatchConfig,
    MatchEndMessage,
    MatchEventMessage,
    MatchScore,
    MatchStartMessage,
    MatchStats,
    PlayerInfo,
    TeamSide,
    WebSocketMessage,
)

__all__ = [
    "Character",
    "CharacterCreate",
    "CharacterUpdate",
    "EmotionalStats",
    "GrowthArc",
    "Team",
    "TeamCreate",
    "TeamUpdate",
    "TeamValues",
    "GeoLocation",
    "Match",
    "MatchCreate",
    "MatchUpdate",
    "TurningPoint",
    "Episode",
    "EpisodeCreate",
    "EpisodeUpdate",
    "Quote",
    "QuoteCreate",
    "QuoteUpdate",
    "QuoteTheme",
    "BelieveRequest",
    "BelieveResponse",
    "ConflictRequest",
    "ConflictResolution",
    "ReframeRequest",
    "ReframeResponse",
    "PressConferenceRequest",
    "PressConferenceResponse",
    "CoachingPrinciple",
    "Biscuit",
    "PepTalkChunk",
    "MatchCommentaryEvent",
    # Team Members (Union Types / oneOf)
    "TeamMember",
    "TeamMemberCreate",
    "Player",
    "PlayerBase",
    "PlayerUpdate",
    "Coach",
    "CoachBase",
    "CoachUpdate",
    "MedicalStaff",
    "MedicalStaffBase",
    "MedicalStaffUpdate",
    "EquipmentManager",
    "EquipmentManagerBase",
    "EquipmentManagerUpdate",
    "MemberType",
    "Position",
    "CoachSpecialty",
    "MedicalSpecialty",
    # WebSocket Models (Live Match Simulation)
    "LiveMatchEvent",
    "LiveMatchEventType",
    "MatchConfig",
    "MatchScore",
    "MatchStats",
    "PlayerInfo",
    "TeamSide",
    "WebSocketMessage",
    "MatchStartMessage",
    "MatchEventMessage",
    "MatchEndMessage",
    "ErrorMessage",
]
