"""Pydantic models for the Ted Lasso API."""

from app.models.characters import (
    Character,
    CharacterCreate,
    CharacterUpdate,
    EmotionalStats,
    GrowthArc,
)
from app.models.teams import Team, TeamCreate, TeamUpdate, TeamValues, GeoLocation
from app.models.matches import Match, MatchCreate, MatchUpdate, TurningPoint
from app.models.episodes import Episode, EpisodeCreate, EpisodeUpdate
from app.models.quotes import Quote, QuoteCreate, QuoteUpdate, QuoteTheme
from app.models.interactive import (
    BelieveRequest,
    BelieveResponse,
    ConflictRequest,
    ConflictResolution,
    ReframeRequest,
    ReframeResponse,
    PressConferenceRequest,
    PressConferenceResponse,
    CoachingPrinciple,
    Biscuit,
    PepTalkChunk,
    MatchCommentaryEvent,
)
from app.models.team_members import (
    TeamMember,
    TeamMemberCreate,
    Player,
    PlayerBase,
    PlayerUpdate,
    Coach,
    CoachBase,
    CoachUpdate,
    MedicalStaff,
    MedicalStaffBase,
    MedicalStaffUpdate,
    EquipmentManager,
    EquipmentManagerBase,
    EquipmentManagerUpdate,
    MemberType,
    Position,
    CoachSpecialty,
    MedicalSpecialty,
)
from app.models.websocket import (
    LiveMatchEvent,
    LiveMatchEventType,
    MatchConfig,
    MatchScore,
    MatchStats,
    PlayerInfo,
    TeamSide,
    WebSocketMessage,
    MatchStartMessage,
    MatchEventMessage,
    MatchEndMessage,
    ErrorMessage,
)

__all__ = [
    "Character",
    "CharacterCreate",
    "CharacterUpdate",
    "EmotionalStats",
    "GrowthArc",
    "Team",
    "TeamCreate",
    "TeamUpdate",
    "TeamValues",
    "GeoLocation",
    "Match",
    "MatchCreate",
    "MatchUpdate",
    "TurningPoint",
    "Episode",
    "EpisodeCreate",
    "EpisodeUpdate",
    "Quote",
    "QuoteCreate",
    "QuoteUpdate",
    "QuoteTheme",
    "BelieveRequest",
    "BelieveResponse",
    "ConflictRequest",
    "ConflictResolution",
    "ReframeRequest",
    "ReframeResponse",
    "PressConferenceRequest",
    "PressConferenceResponse",
    "CoachingPrinciple",
    "Biscuit",
    "PepTalkChunk",
    "MatchCommentaryEvent",
    # Team Members (Union Types / oneOf)
    "TeamMember",
    "TeamMemberCreate",
    "Player",
    "PlayerBase",
    "PlayerUpdate",
    "Coach",
    "CoachBase",
    "CoachUpdate",
    "MedicalStaff",
    "MedicalStaffBase",
    "MedicalStaffUpdate",
    "EquipmentManager",
    "EquipmentManagerBase",
    "EquipmentManagerUpdate",
    "MemberType",
    "Position",
    "CoachSpecialty",
    "MedicalSpecialty",
    # WebSocket Models (Live Match Simulation)
    "LiveMatchEvent",
    "LiveMatchEventType",
    "MatchConfig",
    "MatchScore",
    "MatchStats",
    "PlayerInfo",
    "TeamSide",
    "WebSocketMessage",
    "MatchStartMessage",
    "MatchEventMessage",
    "MatchEndMessage",
    "ErrorMessage",
]
