"""Pydantic models for the Ted Lasso API."""

from app.models.characters import (
    Character,
    CharacterCreate,
    CharacterUpdate,
    EmotionalStats,
    GrowthArc,
)
from app.models.teams import Team, TeamCreate, TeamUpdate, TeamValues
from app.models.matches import Match, MatchCreate, MatchUpdate, TurningPoint
from app.models.episodes import Episode, EpisodeCreate, EpisodeUpdate
from app.models.quotes import Quote, QuoteCreate, QuoteUpdate, QuoteTheme
from app.models.interactive import (
    BelieveRequest,
    BelieveResponse,
    ConflictRequest,
    ConflictResolution,
    ReframeRequest,
    ReframeResponse,
    PressConferenceRequest,
    PressConferenceResponse,
    CoachingPrinciple,
    Biscuit,
    PepTalkChunk,
    MatchCommentaryEvent,
)
from app.models.data_types import (
    DataTypesShowcase,
    DataTypesShowcaseCreate,
    DataTypesShowcaseUpdate,
    GeoLocation,
    MonetaryAmount,
    ContactInfo,
    FileMetadata,
    FileUploadResponse,
    BinaryDataRequest,
    BinaryDataResponse,
    ContentCollection,
    TextContent,
    ImageContent,
    LinkContent,
    TimeRange,
    DateRange,
    Priority,
    FileType,
    Currency,
)

__all__ = [
    "Character",
    "CharacterCreate",
    "CharacterUpdate",
    "EmotionalStats",
    "GrowthArc",
    "Team",
    "TeamCreate",
    "TeamUpdate",
    "TeamValues",
    "Match",
    "MatchCreate",
    "MatchUpdate",
    "TurningPoint",
    "Episode",
    "EpisodeCreate",
    "EpisodeUpdate",
    "Quote",
    "QuoteCreate",
    "QuoteUpdate",
    "QuoteTheme",
    "BelieveRequest",
    "BelieveResponse",
    "ConflictRequest",
    "ConflictResolution",
    "ReframeRequest",
    "ReframeResponse",
    "PressConferenceRequest",
    "PressConferenceResponse",
    "CoachingPrinciple",
    "Biscuit",
    "PepTalkChunk",
    "MatchCommentaryEvent",
    # Data types showcase
    "DataTypesShowcase",
    "DataTypesShowcaseCreate",
    "DataTypesShowcaseUpdate",
    "GeoLocation",
    "MonetaryAmount",
    "ContactInfo",
    "FileMetadata",
    "FileUploadResponse",
    "BinaryDataRequest",
    "BinaryDataResponse",
    "ContentCollection",
    "TextContent",
    "ImageContent",
    "LinkContent",
    "TimeRange",
    "DateRange",
    "Priority",
    "FileType",
    "Currency",
]
